version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: banking
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: banking-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: bankuser
      PMA_PASSWORD: bankpass

volumes:
  mysql_data:

